UserManagerService.Api/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UserManagerService.Shared.Constants;

namespace UserManagerService.Api.Controllers
{
    [Authorize(Roles = RoleConstants.ADMIN)]
    public class AdminController : Controller
    {
        public IActionResult Users() => View();

        public IActionResult Roles() => View();
    }
}

UserManagerService.Api/Controllers/Api/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;
using UserManagerService.Entities;
using UserManagerService.Services.Interfaces;
using UserManagerService.Shared.Constants;
using UserManagerService.Shared.Interfaces.Shared;
using UserManagerService.Shared.Models;
using UserManagerService.Shared.Models.Roles;
using UserManagerService.Shared.Models.User;

namespace UserManagerService.Api.Controllers
{
    [Route("api/users")]
    public class UserController : BaseController
    {
        private readonly ICompanyService _companyService;
        private readonly SignInManager<User> _signInManager;
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;
        private readonly IAuthHelper _auth;
        public UserController(ICompanyService companyService, SignInManager<User> signInManager, IAuthHelper auth, ILogger<UserController> logger, IUserService userService, IRoleService roleService) : base(logger)
        {
            _companyService = companyService;
            _signInManager = signInManager;
            _auth = auth;
            _userService = userService;
            _roleService = roleService;
        }

        [HttpGet]
        public async Task<IActionResult> GetCompanyUsers()
        {
            var users = await _companyService.GetCompanyUsersAsync();
            return Ok(users);
            // return CustomResponse.Success("Users fetched successfully", users);
        }

        [Authorize(Roles = RoleConstants.ADMIN)]
        [HttpGet("admin")]
        public async Task<IActionResult> GetUsers()
        {
            var users = await _userService.GetUsersAsync();
            return CustomResponse.Success("Users fetched successfully", users);
        }

        [AllowAnonymous]
        [HttpPost("/api/v4/login")]
        public async Task<IActionResult> LoginWithSession([FromBody] LoginInputWithSession input)
        {
            var output = await _userService.GetAuthTokenWithSessionIdAsync(input);

            if (string.IsNullOrEmpty(output.AccessToken))
                return CustomResponse.Fail(ResponseMessages.AuthenticationFailed);
            else
                return CustomResponse.Success(ResponseMessages.UserAuthenticated, output);
        }

        [AllowAnonymous]
        [HttpPost("/api/v3/login")] // Get SessionId to redirect
        public async Task<IActionResult> LoginToRedirect([FromBody] LoginToCompanyInputModel input, string returnUrl)
        {
            var output = await _userService.GetAuthSessionToRedirectAsync(input, returnUrl);

            if (output.SessionId == Guid.Empty)
                return CustomResponse.Fail(ResponseMessages.AuthenticationFailed);
            else
                return CustomResponse.Success(ResponseMessages.UserAuthenticated, output);

        }

        [AllowAnonymous]
        [HttpPost("/api/v2/login")] // Company Login
        public async Task<IActionResult> Login([FromBody] LoginToCompanyInputModel input)
        {
            var output = await _userService.GetAuthTokenAsync(input);

            if (output.Companies is not null)
                return CustomResponse.Success(ResponseMessages.UserAuthenticated, new { output.Companies, output.SessionId });

            if (string.IsNullOrEmpty(output.AuthTokens.AccessToken) || string.IsNullOrEmpty(output.AuthTokens.RefreshToken))
                return CustomResponse.Fail(ResponseMessages.AuthenticationFailed);
            else
                return CustomResponse.Success(ResponseMessages.UserAuthenticated, output.AuthTokens);

        }

        [AllowAnonymous]
        [HttpPost("/api/v1/login")] // Simple
        public async Task<IActionResult> Login([FromBody] LoginInputModel input)
        {
            var output = await _userService.GetAuthTokenAsync(input);
            var result = (string.IsNullOrEmpty(output.AccessToken))
                    ? ResponseModel.Fail(ResponseMessages.AuthenticationFailed)
                    : ResponseModel.Success(ResponseMessages.UserAuthenticated, output);
            return Ok(result);
        }

        [AllowAnonymous]
        [HttpPost("/api/refresh-token")]
        public async Task<IActionResult> RefreshToken([FromBody] RefreshTokenInput input)
        {
            var tokens = await _userService.RefreshTokenAsync(input);

            return tokens != null
                 ? CustomResponse.Success(ResponseMessages.TokensRefreshed, tokens)
                 : CustomResponse.Fail(ResponseMessages.RefreshTokenFailed);
        }

        [AllowAnonymous]
        [HttpPost("/api/register")]
        public async Task<IActionResult> Register([FromBody] RegisterModel input)
        {
            var model = await _userService.RegisterUserAsync(input);
            return CustomResponse.Success(ResponseMessages.UserCreated, model);
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, [FromBody] UserInputModel input)
        {
            var model = await _userService.UpdateUserAsync(id, input);
            return CustomResponse.Success("User updated successfully", model);
        }

        [Authorize(Roles = RoleConstants.ADMIN)]
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _userService.DeleteUserAsync(id);
            return CustomResponse.Success("User deleted successfully");
        }

        [HttpGet("/api/me")]
        public async Task<IActionResult> Me() => Ok(await _userService.GetMyProfileAsync());

        [HttpGet("/api/sessions")]
        public async Task<IActionResult> LoginHistory([FromQuery] LoginSessionInputModel input)
        {
            var loginHistory = await _userService.GetLoginSessionsAsync(input);
            return CustomResponse.Success("Login history fetched successfully", loginHistory);
        }

        //[ApiKey]
        [AllowAnonymous]
        [HttpPost("profiles")]
        public async Task<IActionResult> Profiles([FromBody] GetUserProfilesModel input)
        {
            var profiles = await _userService.GetUserProfilesByIdsAsync(input.UserIds);
            return Ok(ResponseModel.Success(ResponseMessages.UserProfilesFetched, profiles));
        }

        [HttpPost("{UserId}/roles")]
        public async Task<IActionResult> AssignRoles([FromBody] UserRoleInputModel input)
        {
            var model = await _roleService.AssignRolesToUserAsync(input);
            return CustomResponse.Success("Roles assigned to user successfully", model);
        }

        [HttpDelete("{UserId}/roles")]
        public async Task<IActionResult> RemoveRoles([FromBody] UserRoleInputModel input)
        {
            await _roleService.RemoveRolesFromUserAsync(input);
            return CustomResponse.Success("Roles removed from user successfully");
        }
    }
}

UserManagerService.Api/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UserManagerService.Api.Attributes;
using UserManagerService.Entities;
using UserManagerService.Interfaces.Repositories;
using UserManagerService.Services.Interfaces;
using UserManagerService.Shared.Constants;
using UserManagerService.Shared.Interfaces.Services;
using UserManagerService.Shared.Interfaces.Shared;
using UserManagerService.Shared.Models;
using UserManagerService.Shared.Models.User;

namespace UserManagerService.Api.Controllers
{
    [ApiController]
    [Route("api/users")]
    public class UserController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly SignInManager<User> _signInManager;
        private readonly IUserService _userService;
        private readonly IAuth _auth;
        public UserController(IUnitOfWork unitOfWork, SignInManager<User> signInManager, IUserContext userContext, IAuth auth, ILogger<UserController> logger, IUserService userService) : base(userContext, logger)
        {
            _unitOfWork = unitOfWork;
            _signInManager = signInManager;
            _auth = auth;
            _userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> GetCompanyUsers()
        {
            var users = await _unitOfWork.Query<CompanyUser>(u => u.CompanyId == _userContext.CompanyId).Include(o => o.User)
                .Select(u => new UserModel
                {
                    Id = u.User.Id,
                    CreatedAt = u.User.CreatedAt,
                    IsConnected = u.User.IsConnected,
                    Name = u.User.Name,
                    Surname = u.User.Surname,
                    UpdatedAt = u.User.UpdatedAt,
                    Username = u.User.UserName
                }).ToListAsync();

            return Ok(users);
        }

        [Authorize(Roles = Roles.ADMIN)]
        [HttpGet("admin")]
        public async Task<IActionResult> GetUsers()
        {
            var users = await _unitOfWork.Query<User>()
                .Select(u => new UserModel
                {
                    Id = u.Id,
                    CreatedAt = u.CreatedAt,
                    IsConnected = u.IsConnected,
                    Name = u.Name,
                    Surname = u.Surname,
                    UpdatedAt = u.UpdatedAt,
                    Username = u.UserName
                }).ToListAsync();

            return Ok(users);
        }

        [AllowAnonymous]
        [HttpPost("/api/login")]
        public async Task<IActionResult> Login([FromBody] LoginModel input)
        {
            _logger.LogInformation($"User {_userContext.Username} is getting the token");
            if (string.IsNullOrEmpty(input.Username) || string.IsNullOrEmpty(input.Password))
                return Ok(ResponseModel.Fail(ResponseMessages.InvalidInput));

            var tokens = new AuthTokenModel();
            var user = await _signInManager.UserManager.FindByNameAsync(input.Username);
            if (user is null)
                return Ok(ResponseModel.Fail(ResponseMessages.WrongCredentials));

            var signedIn = await _signInManager.PasswordSignInAsync(user, input.Password, true, false);
            if (signedIn.Succeeded)
            {
                await _signInManager.SignOutAsync(); // remove the cookie
                var roles = (List<string>)await _signInManager.UserManager.GetRolesAsync(user);

                if (input.CompanyId is not null)
                {
                    // check you beGuid to the company
                }

                // Get default company
                var company = input.CompanyId is null ?
                    await _unitOfWork.Query<CompanyUser>(o => o.UserId == user.Id)
                    .Include(o => o.Company).Select(o => (Company)o.Company).FirstOrDefaultAsync()
                    : await _unitOfWork.Query<CompanyUser>(o => o.UserId == user.Id && o.CompanyId == input.CompanyId)
                    .Include(o => o.Company).Select(o => (Company)o.Company).SingleOrDefaultAsync();

                tokens = _auth.CreateSecurityToken(user.Id, user.UserName, roles.Select(r => r.ToUpper()).ToList(), company.Id, company.Name);
            }
            var result = (string.IsNullOrEmpty(tokens.AccessToken) || string.IsNullOrEmpty(tokens.RefreshToken))
                    ? ResponseModel.Fail(ResponseMessages.AuthenticationFailed)
                    : ResponseModel.Success(ResponseMessages.UserAuthenticated, tokens);
            return Ok(result);
        }

        [AllowAnonymous]
        [HttpPost("/api/refresh-token")]
        public async Task<IActionResult> RefreshToken([FromBody] RefreshTokenInput input)
        {
            _logger.LogInformation($"User is trying to refresh access token with refresh token : {input.RefreshToken}");

            var cachedToken = _auth.GetCachedRefreshTokenWithRequestIpValidation(input.RefreshToken);
            if (cachedToken is null)
                return Ok(ResponseModel.Fail(ResponseMessages.InvalidRefreshToken));

            if (!_auth.RevokeCachedRefreshToken(input.RefreshToken))
                return Ok(ResponseModel.Fail(ResponseMessages.RefreshTokenFailed));

            //var user = await _userRepository.GetUserByIdAsync();

            var user = await _signInManager.UserManager.FindByIdAsync(cachedToken.UserId.ToString());
            if (user is null)
                return Ok(ResponseModel.Fail(ResponseMessages.UserNotFound));

            var roles = (List<string>)await _signInManager.UserManager.GetRolesAsync(user);
            var company = await _unitOfWork.Query<CompanyUser>(o => o.UserId == user.Id)
                    .Include(o => o.Company).Select(o => (Company)o.Company).FirstOrDefaultAsync();

            var tokens = _auth.CreateSecurityToken(user.Id, user.UserName, roles, company.Id, company.Name);

            var result = tokens != null
                ? ResponseModel.Success(ResponseMessages.TokensRefreshed, tokens)
                : ResponseModel.Fail(ResponseMessages.RefreshTokenFailed);
            return Ok(result);
        }

        [Authorize(Roles = Roles.ADMIN)]
        [HttpPost("/api/register")]
        public async Task<IActionResult> Register([FromBody] RegisterModel input)
        {
            _logger.LogInformation($"User with id: {_userContext.UserId} is creating a user with username {input.Username}");
            if (string.IsNullOrEmpty(input.Username) || string.IsNullOrEmpty(input.Password) || string.IsNullOrEmpty(input.Username))
            {
                _logger.LogInformation("Password or username is null or empty");
                return Ok(ResponseModel.Fail(ResponseMessages.WrongCredentials));
            }

            // TODO check if org exists

            var user = await _signInManager.UserManager.FindByNameAsync(input.Username);
            if (user != null)
                return Ok(ResponseModel.Fail(ResponseMessages.EmailExists));
            user = new User
            {
                Email = input.Email,
                NormalizedEmail = input.Email.ToUpper(),
                UserName = input.Username,
                NormalizedUserName = input.Email.ToUpper(),
                AccessFailedCount = 0,
                EmailConfirmed = true,
                Name = input.Name,
                Surname = input.Surname,
                LockoutEnabled = false
            };

            var ir = await _signInManager.UserManager.CreateAsync(user, input.Password);

            if (ir.Succeeded)
            {
                //var createdUser = await _userRepository.GetUserByUsernameAsync(input.Username);
                _logger.LogInformation($"Created user `{input.Username}` successfully");

                //Auto add to company
                var orgUser = new CompanyUser()
                {
                    CompanyId = input.CompanyId == Guid.Empty ? _userContext.CompanyId : input.CompanyId,
                    UserId = user.Id,
                    CreatorId = _userContext.UserId,
                };
                await _unitOfWork.AddAsync(orgUser);
                await _unitOfWork.SaveAsync();

                var model = new UserProfile
                {
                    Id = user.Id,
                    Name = user.Name,
                    Username = user.UserName,
                    Surname = user.Surname,
                    CompanyId = orgUser.CompanyId
                };
                return Ok(ResponseModel.Success(ResponseMessages.UserCreated, model));
            }
            else
            {
                string errors = "";
                ir.Errors.ToList().ForEach(e => { errors += $"{e.Code} {e.Description},"; });
                _logger.LogError($"Failed to create user: {errors}");
                return Ok(ResponseModel.Fail(ResponseMessages.FailedToCreatUser));
            }
        }

        [Authorize(Roles = Roles.ADMIN)]
        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, [FromBody] UserInputModel input)
        {
            var model = await _userService.UpdateUserAsync(id, input);
            return CustomResponse.Success("User updated successfully", model);
        }

        [Authorize(Roles = Roles.ADMIN)]
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _userService.DeleteUserAsync(id);
            return CustomResponse.Success("User deleted successfully");
        }

        [HttpGet("/api/me")]
        public async Task<IActionResult> Me() => Ok(await _userService.GetUserProfileAsync(_userContext.UserId));

        [HttpPost("profiles/get")]

UserManagerService.Api/Views/Shared/Stats.cshtml
<div class="d-flex flex-wrap flex-stack">
    <!--begin::Wrapper-->
    <div class="d-flex flex-column flex-grow-1 pe-8">
        <!--begin::Stats-->
        <div class="d-flex flex-wrap">
            <!--begin::Stat-->
            <div class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-6 mb-3">
                <!--begin::Number-->
                <div class="d-flex align-items-center">
                    <!--begin::Svg Icon | path: icons/duotone/Navigation/Arrow-up.svg-->
                    <span class="svg-icon svg-icon-3 svg-icon-success me-2">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <polygon points="0 0 24 0 24 24 0 24" />
                                <rect fill="#000000" opacity="0.5" x="11" y="5" width="2" height="14" rx="1" />
                                <path d="M6.70710678,12.7071068 C6.31658249,13.0976311 5.68341751,13.0976311 5.29289322,12.7071068 C4.90236893,12.3165825 4.90236893,11.6834175 5.29289322,11.2928932 L11.2928932,5.29289322 C11.6714722,4.91431428 12.2810586,4.90106866 12.6757246,5.26284586 L18.6757246,10.7628459 C19.0828436,11.1360383 19.1103465,11.7686056 18.7371541,12.1757246 C18.3639617,12.5828436 17.7313944,12.6103465 17.3242754,12.2371541 L12.0300757,7.38413782 L6.70710678,12.7071068 Z" fill="#000000" fill-rule="nonzero" />
                            </g>
                        </svg>
                    </span>
                    <!--end::Svg Icon-->
                    <div class="fs-2 fw-bolder" data-kt-countup="true" data-kt-countup-value="4500" data-kt-countup-prefix="$">0</div>
                </div>
                <!--end::Number-->
                <!--begin::Label-->
                <div class="fw-bold fs-6 text-gray-400">Earnings</div>
                <!--end::Label-->
            </div>
            <!--end::Stat-->
            <!--begin::Stat-->
            <div class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-6 mb-3">
                <!--begin::Number-->
                <div class="d-flex align-items-center">
                    <!--begin::Svg Icon | path: icons/duotone/Navigation/Arrow-down.svg-->
                    <span class="svg-icon svg-icon-3 svg-icon-danger me-2">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <polygon points="0 0 24 0 24 24 0 24" />
                                <rect fill="#000000" opacity="0.5" x="11" y="5" width="2" height="14" rx="1" />
                                <path d="M6.70710678,18.7071068 C6.31658249,19.0976311 5.68341751,19.0976311 5.29289322,18.7071068 C4.90236893,18.3165825 4.90236893,17.6834175 5.29289322,17.2928932 L11.2928932,11.2928932 C11.6714722,10.9143143 12.2810586,10.9010687 12.6757246,11.2628459 L18.6757246,16.7628459 C19.0828436,17.1360383 19.1103465,17.7686056 18.7371541,18.1757246 C18.3639617,18.5828436 17.7313944,18.6103465 17.3242754,18.2371541 L12.0300757,13.3841378 L6.70710678,18.7071068 Z" fill="#000000" fill-rule="nonzero" transform="translate(12.000003, 14.999999) scale(1, -1) translate(-12.000003, -14.999999)" />
                            </g>
                        </svg>
                    </span>
                    <!--end::Svg Icon-->
                    <div class="fs-2 fw-bolder" data-kt-countup="true" data-kt-countup-value="75">0</div>
                </div>
                <!--end::Number-->
                <!--begin::Label-->
                <div class="fw-bold fs-6 text-gray-400">Projects</div>
                <!--end::Label-->
            </div>
            <!--end::Stat-->
            <!--begin::Stat-->
            <div class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-6 mb-3">
                <!--begin::Number-->
                <div class="d-flex align-items-center">
                    <!--begin::Svg Icon | path: icons/duotone/Navigation/Arrow-up.svg-->
                    <span class="svg-icon svg-icon-3 svg-icon-success me-2">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <polygon points="0 0 24 0 24 24 0 24" />
                                <rect fill="#000000" opacity="0.5" x="11" y="5" width="2" height="14" rx="1" />
                                <path d="M6.70710678,12.7071068 C6.31658249,13.0976311 5.68341751,13.0976311 5.29289322,12.7071068 C4.90236893,12.3165825 4.90236893,11.6834175 5.29289322,11.2928932 L11.2928932,5.29289322 C11.6714722,4.91431428 12.2810586,4.90106866 12.6757246,5.26284586 L18.6757246,10.7628459 C19.0828436,11.1360383 19.1103465,11.7686056 18.7371541,12.1757246 C18.3639617,12.5828436 17.7313944,12.6103465 17.3242754,12.2371541 L12.0300757,7.38413782 L6.70710678,12.7071068 Z" fill="#000000" fill-rule="nonzero" />
                            </g>
                        </svg>
                    </span>
                    <!--end::Svg Icon-->
                    <div class="fs-2 fw-bolder" data-kt-countup="true" data-kt-countup-value="60" data-kt-countup-prefix="%">0</div>
                </div>
                <!--end::Number-->
                <!--begin::Label-->
                <div class="fw-bold fs-6 text-gray-400">Success Rate</div>
                <!--end::Label-->
            </div>
            <!--end::Stat-->
        </div>
        <!--end::Stats-->
    </div>
    <!--end::Wrapper-->
    <!--begin::Progress-->
    <div class="d-flex align-items-center w-200px w-sm-300px flex-column mt-3">
        <div class="d-flex justify-content-between w-100 mt-auto mb-2">
            <span class="fw-bold fs-6 text-gray-400">Profile Compleation</span>
            <span class="fw-bolder fs-6">50%</span>
        </div>
        <div class="h-5px mx-3 w-100 bg-light mb-3">
            <div class="bg-success rounded h-5px" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
    <!--end::Progress-->
</div>

UserManagerService.Api/Views/Shared/_SideBarPartial.cshtml
@inject UserManagerService.Shared.Interfaces.Services.IUserContext userContext
<div class="sidebar mb-5">
    @*Sidebar user panel (optional)*@
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a asp-controller="User" asp-action="Profile" class="d-block" id="identity"> @userContext.Username </a>
        </div>
    </div>

    <!-- SidebarSearch Form -->
    <div class="form-inline mt-5">
        <div class="input-group" data-widget="sidebar-search">
            <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-sidebar">
                    <i class="fas fa-search fa-fw"></i>
                </button>
            </div>
        </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->


            <li class="nav-item">
                <a asp-controller="Interaction" asp-action="Requests" class="nav-link">
                    <i class="nav-icon fas fa-share"></i>
                    <p>
                        Requests
                        @*<span class="right badge badge-danger">New</span>*@
                    </p>
                </a>
            </li>

            @if (User.IsInRole("ADMIN"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="Users">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Users
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="Companies">
                        <i class="nav-icon fas fa-building"></i>
                        <p>
                            Companies
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="Insurances">
                        <i class="nav-icon fas fa-money-check-alt"></i>
                        <p>
                            Insurances
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="Providers">
                        <i class="nav-icon fas fa-hospital-user"></i>
                        <p>
                            Providers
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="Facilities">
                        <i class="nav-icon fas fa-hospital"></i>
                        <p>
                            Facilities
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="DocumentTypes">
                        <i class="nav-icon fas fa-file-alt"></i>
                        <p>
                            Document Types
                        </p>
                    </a>
                </li>

            }

            @*<li class="nav-item">
            <a asp-controller="Home" asp-action="Index" class="nav-link">
                <i class="nav-icon fas fa-users"></i>
                <p>
                    Requests
                    <span class="right badge badge-danger">New</span>
                </p>
            </a>
        </li>*@


            <li class="nav-item">
                <form class="form-inline" asp-controller="Home" asp-action="Logout" method="post" asp-route-returnUrl="@Url.Action(" Index", "Home" , new { area="" })" id="logout_form">
                    <a class="nav-link" href="javascript:;" id="logout_button">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>
                            Logout
                        </p>
                    </a>
                </form>
            </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>